TEEM-15849: Error while generating encrypted json
What?
- Fixed issue for generating encrypted json. Issue is caused by difference between string/bytes in Python versions. In python 2
cryptography lib return bytes (`str` type) which have all string methods and JSON
serializable. In python 3 it returns bytes which is failing during json serialization
- `force_text` allows to keep same behavior in Python 2 (str remain str) but fix it in python 3

Why?
Simplified version in Python 3 (in Python 2 it executes well):

```
>>> import json
>>> json.dumps({'a': b'ssss'})
TypeError: Object of type bytes is not JSON serializable
```